import type { Metadata } from "next";
import "./globals.css";
import { Container } from "@/components/container";

import Footer from "@/components/footer/page";
import Header from "@/components/Header/page";







export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
      <Container>
        <Header/>

        {children}

        </Container>
      </body>
    </html>
  );
}
