import type { Metadata } from "next";
import "./globals.css";
import { Container } from "@/components/container";
import { Header } from "@/components/Header";
import { Hero } from "@/components/page/Hero";
import { About } from "@/components/page/About";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body>
       <Container>
        <Header/>
        <Hero/>
        <About/>
        {children}
        </Container>
      </body>
    </html>
  );
}
